---
title: "Joining data for one dataset on airports in each county"
author: "Whitney Mgbara"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Libraries
```{r}
require(tidyverse)
require(readr)


require(ggmap)
```


Airport lon, lat data
```{r}

airports <- read.csv("airports1.csv")

airports <- filter(airports, Country == "United States")

names(airports)[names(airports)=="City"] <- "city"


```



Commercial 2018 and 2017 enplanements for US airports
```{r}

# getwd()
enplane <- read.csv("cy18-commercial-service-enplanements.csv")
airports <- filter(airports, IATA != "NA")

# iata_city_country <- filter(iata_city_country, Country == "USA")


```



We will join it with the airport dataset
```{r}

airport_complete <- left_join(enplane, airports, by = c("IATA", "city")) %>%
  filter(Longitude != "NA")  %>%
  # filter(Country == "United States") %>%
  select( c("IATA" , "ICAO", "city", "ST", "Airport.Name",
             "Type","CY.18.Enplanements", "CY.17.Enplanements",
             "X..Change", "Longitude", "Latitude", "Altitude",
             "Timezone",
             "DST", "Tz.database", "Source"))



# airport_complete2 <- left_join(enplane, airports, by = c("city", "IATA")) 


```


```{r}

qmplot(Longitude, Latitude, data = airport_complete, colour = I('red'), size = I(1), darken = .3)

```




```{r}

city_state <- read.csv("city_state.csv")

airport_complete3 <- left_join(city_state, airport_complete, by = c("city", "ST")) %>%
  filter(Longitude != "NA") %>%
  select(
    c("city", "city_ascii", "ST", "state_name",
      "IATA", "Airport.Name", "CY.18.Enplanements",
      "CY.17.Enplanements", "X..Change", "Latitude", 
      "Longitude", "Altitude", "Timezone", "DST",
      "Tz.database", "Type", "Source")
  )



```




Adding counties in
```{r}

uscities <- read.csv("uscities.csv")

airport_complete4 <- left_join(uscities, airport_complete3, by = c("city","city_ascii", "state_name", "ST")) %>%
  dplyr::select( -c("county_name","county_fips_all","lat", "lng",
                    "source", "timezone", "zips", 
                    "population", "density", "military",
                    "incorporated", "ranking", "id") ) %>%
  filter(Longitude != "NA")
  
airport_complete4$CY.18.Enplanements <- gsub(",","", airport_complete4$CY.18.Enplanements)
airport_complete4$CY.18.Enplanements <- as.numeric(airport_complete4$CY.18.Enplanements)

airport_complete4$CY.17.Enplanements <- gsub(",","", airport_complete4$CY.17.Enplanements)
airport_complete4$CY.17.Enplanements <- as.numeric(airport_complete4$CY.17.Enplanements)

names(airport_complete4)[names(airport_complete4)=="county_fips"] <- "FIPS"

```



Final result
```{r}
# head(airport_complete4)

write.csv(airport_complete4,"MyairportData.csv", row.names = FALSE)
```

