---
title: "Adding Lat and Long to Case Data"
author: "Whitney Mgbara"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Libraries
```{r}

require(tidyverse)
require(readr)

require(ggplot2)

require(ggmap)
require(sf) 
require(rgdal)
require(raster)
```



Case and geo county data
```{r}

geocounties <- read.csv("county_lat_lon.csv", header=TRUE, stringsAsFactors=F)
geocounties <- dplyr::select(geocounties, -c("ID", "County", "County.Seat.s."))


geocounties2 <- read.csv("uscities.csv")
names(geocounties2)[names(geocounties2)=="county_fips"] <- "FIPS"
names(geocounties2)[names(geocounties2)=="ST"] <- "State"

```


Join with case data and plot
```{r}
day25 <- read.csv("day25.csv", header=TRUE, stringsAsFactors=F)


```


```{r}

# with case data
geoday25_1 <- left_join(day25, geocounties, by = c("FIPS", "State")) 



# Without case data
geoday25_2 <- left_join(day25, geocounties2, by = c("FIPS", "State")) %>%
  dplyr::select("FIPS", "Name", "city", "State", "state_name", 
                "lat", "lng", "timezone", "zips")
names(geoday25_2)[names(geoday25_2)=="State"] <- "ST"



```



Join with airport data
```{r}

airportss <- read.csv("firstAirportData.csv")
# names(airportss)[names(airportss)=="ST"] <- "State"


airport_up <- merge(airportss,day25) %>%
  dplyr::select(
    -c("city_ascii", "county_name_all", "State")
    )
airport_up$day25 <- 1 


# I want to put together the airports that match with a county in the day25 dataset and the all airports in the US
county_air <- data.frame(Longitude = airport_up$Longitude, Latitude = airport_up$Latitude, day25 = airport_up$day25)

terst <- left_join(airportss, county_air, by=c("Longitude", "Latitude"))

for(i in (1:nrow(terst))){
  if(is.na(terst$day25[i])){
    terst$day25[i] <- 0
  }
}  
  

# airports_update <- left_join(geoday25_2, airportss, by = c("ST", "FIPS", "city", "state_name")) %>%
#   filter(Latitude != "NA") %>%
#   dplyr::select(
#     -c("lat", "lng", "zips", "city_ascii", "county_name_all", 
#        "timezone")
#   )

```



Final result
```{r}
# head(airport_complete4)

write.csv(terst,"MyairportData.csv", row.names = FALSE)

write.csv(geoday25_2,"Counties_Allcities.csv", row.names = FALSE)

write.csv(geoday25_1,"Mygeday25Data.csv", row.names = FALSE)
```


Plot the new dataset with cases
```{r}
qmplot(Longitude, Latitude, data = geoday25_1, colour = I('red'), size = I(0.5), darken = .3)
```



Plot all airports
```{r}
qmplot(Longitude, Latitude, data = airportss, colour = I('red'), size = I(0.5), darken = .3)
```




Plot dataset of the airports for counties that had cases
```{r}
qmplot(Longitude, Latitude, data = airports_update, colour = I('red'), size = I(0.5), darken = .3)
```



Plotting the lat and long for counties based on the range of values for Day of First Case
```{r}

#Some sample data
x <- sort(runif(100))
dat <- data.frame(x = x,y = x^2 + 1)
# Some external vector for the color scale
col <- sort(rnorm(100))

qplot(x, y, data=dat, colour=col) + scale_colour_gradient(low="red", high="blue")

#Some sample data
x <- sort(runif(100))
dat <- data.frame(x = x,y = x^2 + 1)
# Some external vector for the color scale
col <- sort(geoday25_1$DayOfFirstCases)

qplot(Longitude, Latitude, data=geoday25_1, colour=col) + scale_colour_gradient(low="red", high="blue")

```




```{r}

partyUSA <- st_read("C:/Users/Whitney/Downloads/USA_adm/USA_adm1.shp")

# partyUSA <- st_read("C:/Users/Whitney/Downloads/cb_2018_us_csa_20m")


plot(partyUSA[7])
```



Averages By metropolitan statistical area
```{r}

metroAreas <- read.csv("metro_stat_area.csv", header=TRUE, stringsAsFactors=F)


test123 <- left_join(geoday25_1, metroAreas, by = "Name") %>%
  filter(State.x == c("NY", "CA")) %>%
  subset(Core_Based_Statistical_Area != "none")

test123$popland <- test123$Population/test123$LandArea


df <- 
  test123 %>% 
  group_by(Core_Based_Statistical_Area, State.x) %>%
  summarize(DayOfFirstCases = mean(DayOfFirstCases),
            ConfirmedCasesDay25 = sum(ConfirmedCasesDay25),
            CommutingByPublicTransportation =
              mean(CommutingByPublicTransportation), 
            GDP = mean(GDP),
            popland = mean(popland))

df


```



```{r}

testing123 <- data.frame(
  y = log(test123$ConfirmedCasesDay25), 
  x = log(test123$CommutingByPublicTransportation)) 

sp <- ggplot(testing123, aes(x=x, y=y)) +
  geom_point() +
  theme(legend.title = element_blank())
sp 

```



```{r}

plot(testing123$x)
```





