---
title: "Maps"
author: "Whitney Mgbara"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
require(tidyverse)
require(readr)


require(ggmap)
```

#### Data Sources:

US Cities & Counties (us-cities):

- https://simplemaps.com/data/us-cities


Airports:

- https://github.com/datasets/airport-codes

- https://www.census.gov/data/tables/time-series/demo/popest/2010s-total-metro-and-micro-statistical-areas.html#par_textimage

- https://data.humdata.org/dataset/ourairports-usa


Enplanements:

- https://www.faa.gov/airports/planning_capacity/passenger_allcargo_stats/passenger/


Metropolitan statistical areas:

- https://en.wikipedia.org/wiki/California_statistical_areas

- https://en.wikipedia.org/wiki/New_York_statistical_areas

- https://en.wikipedia.org/wiki/Washington_statistical_areas

- https://en.wikipedia.org/wiki/New_Jersey_statistical_areas


Shapefiles:

- diva-gis.org/datadown



```{r}

airports <- read.csv("Visulizations/airports.csv", stringsAsFactors=F)
names(airports)[names(airports)=="municipality"] <- "city"

cities_counties <- read.csv("Visulizations/uscities.csv", stringsAsFactors=F)

city_airports <- 
  cities_counties %>%
  select(-c("id")) %>%
  left_join(airports, cities_counties, by = "city")
  

airport_lat_lon <- 
  city_airports %>%
  filter(iso_country == "US") %>%
  select(-c("city_ascii","id","ident","continent",
            "scheduled_service",
            "gps_code",
            "iata_code","local_code","home_link",
            "wikipedia_link","keywords","continent",
            "scheduled_service","gps_code",
            "iata_code","local_code","home_link",
            "wikipedia_link","keywords","county_fips_all",
            "county_name_all","lat","lng",
            "population","density","source","military",
            "incorporated", "timezone", "ranking","zips","id",
            "name", "iso_country", "iso_region")
            )




# enplanements <- read.csv("Visulizations/enplanements.csv") 
# names(enplanements)[names(enplanements)=="City"] <- "city"

# test <- left_join(cities_counties, enplanements, by="city")
```

Combining usports data and com_enplane data for lat and long
```{r}

usports <- read.csv("Visulizations/us-airports.csv", header=TRUE, stringsAsFactors=F)
names(usports)[names(usports)=="municipality"] <- "city"

com_enplane <- read.csv("Visulizations/cy18-commercial-service-enplanements.csv", header=TRUE, stringsAsFactors=F)
com_enplane <- subset(com_enplane, Locid != "NA")
names(com_enplane)[names(com_enplane)=="Airport.Name"] <- "name"
names(com_enplane)[names(com_enplane)=="Locid"] <- "iata_code"
com_enplane <- gsub(",","",com_enplane)


ports_com_enplane <- usports %>%
  left_join(com_enplane, by=c("iata_code")) %>%
  select( c("id", "city.x", "name.x", "type", "latitude_deg", 
            "longitude_deg", 
            "elevation_ft", "CY.18.Enplanements", 
            "CY.17.Enplanements", "X..Change", "Rank", 
            "score",
            "gps_code", "iata_code", 
            "home_link", "wikipedia_link"))

# subset(ports_enplane, is.na(Rank))
  
```

Combining usports data and all_enplane data for lat and long
```{r}
usports <- read.csv("Visulizations/us-airports.csv", header=TRUE, stringsAsFactors=F)
names(usports)[names(usports)=="municipality"] <- "city"

all_enplane <- read.csv("Visulizations/cy18-all-enplanements.csv", header=TRUE, stringsAsFactors=F)
all_enplane <- subset(all_enplane, Locid != "NA")
names(all_enplane)[names(all_enplane)=="Airport.Name"] <- "name"
names(all_enplane)[names(all_enplane)=="Locid"] <- "iata_code"
all_enplane$CY.18.Enplanements <- gsub(",","", all_enplane$CY.18.Enplanements)

all_enplane$CY.18.Enplanements <- as.numeric(all_enplane$CY.18.Enplanements)


ports_all_enplane <- usports %>%
  left_join(all_enplane, by=c("iata_code", "city")) %>%
  select( c("id", "ST", "city", "name.x", "type",
            "latitude_deg", 
            "longitude_deg", 
            "elevation_ft", "CY.18.Enplanements", 
            "CY.17.Enplanements", "X..Change", "Rank","score",
            "gps_code", "iata_code", 
            "home_link", "wikipedia_link")) 

names(ports_all_enplane)[names(ports_all_enplane)=="ST"] <- "state_id"
```


Combining ports_all_enplane data with uscities for counties
```{r}
cities_counties <- read.csv("Visulizations/uscities.csv", header=TRUE, stringsAsFactors=F)

county_ports <- 
  cities_counties %>%
  select(city, state_id, state_name, county_fips, 
         county_name) %>%
  left_join(ports_all_enplane, by = c("city", "state_id")) %>%
  subset(name.x != "NA")
  
```


Plotting lat and long for county_ports
```{r}
qmplot(longitude_deg, latitude_deg, data = county_ports, colour = I('red'), size = I(0.5), darken = .3)
```


```{r}

county_ports$CY.18.Enplanements <- as.numeric(county_ports$CY.18.Enplanements)

# as.numeric(county_ports$CY.17.Enplanements)
# as.numeric(county_ports$X..Change)
# as.numeric(county_ports$Rank)
# as.numeric(county_ports$score)

df <- 
  county_ports %>% group_by(county_fips, county_name) %>%
    summarize(CY.18.Enplanements = 
                mean(CY.18.Enplanements))

```




```{r}

names(cities_counties)[names(cities_counties)=="county_fips_all"] <- "FIPS"

names(cities_counties)[names(cities_counties)=="state_id"] <- "State"

df <- left_join(day25, cities_counties, by = c("FIPS", "State"))

```


